import type { ChatCompletionMessageParam } from 'openai/src/resources/chat/completions';
import { getPromptTemplate } from '../utils';
import Handlebars from 'handlebars';

/**
 * Prepare command prompt that generated by e2e test report
 * return array of messages to send to be sent to openai as specializations
 */
export const createCommandPrompt = (userCommand: string): Array<ChatCompletionMessageParam> => {
  const systemTemplate = getPromptTemplate('command/template')
  const systemFlows = getPromptTemplate('command/flows')


  const systemContent = Handlebars.compile(systemTemplate)({
    flows: systemFlows.trim()
  })

  return [ {
    role: 'system',
    content: systemContent,
  },
  //   {
  //   'role': 'user',
  //   'content': 'example user command'
  // }, {
  //   'role': 'assistant',
  //   'content': '[\'navigate\',  \'/page\']\n[ \'focus\', \'based on user command\' ]\n[ \'fill\', \'content based on user content\' ]'
  // },
    {
    'role': 'user',
    'content': userCommand
  } ]
}
