interface User {
  id: string; // 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b17';
  name: string; // 'Angelique Morse';
  email: string; // 'benny89@yahoo.com';
  country: string; // 'Bosnia and Herzegovina';
  city: string; // 'Rancho Cordova';
  address: string; // '908 Jack Locks';
  avatarUrl: string; // 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_17.jpg';
  company: string; // 'Wuckert Inc';
  phoneNumber: string; // '500-268-4826';
  role: string; // 'Sales Representative';
  isVerified: boolean; // true;
  status: string; // 'banned';
}

export const useUsersData = (): User[] => {


  return [
    {
      'id': 'eaabfbba-bdd2-4af9-bea6-a6e66dc8ec8a',
      'name': 'Corenda Blowick',
      'email': 'cblowick0@storify.com',
      'country': 'Russia',
      'city': 'Solntsevo',
      'address': 'Suite 34',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_5.jpg',
      'company': 'Wikibox',
      'phoneNumber': '447-678-1752',
      'role': 'Operations Manager',
      'isVerified': true,
      'status': 'pending'
    },
    {
      'id': '8a81596c-1de1-4658-b3c1-996b49baad9e',
      'name': 'Alan Truelove',
      'email': 'atruelove1@census.gov',
      'country': 'Vietnam',
      'city': 'Bến Cầu',
      'address': '15th Floor',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_6.jpg',
      'company': 'Tekfly',
      'phoneNumber': '382-477-9742',
      'role': 'Research Scientist',
      'isVerified': true,
      'status': 'banned'
    },
    {
      'id': '70649cd1-d418-4c68-b861-ebe769e0c655',
      'name': 'Tamar Kervin',
      'email': 'tkervin2@myspace.com',
      'country': 'Poland',
      'city': 'Wisznice',
      'address': 'Suite 70',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_7.jpg',
      'company': 'Skimia',
      'phoneNumber': '766-899-0203',
      'role': 'Business Analyst',
      'isVerified': false,
      'status': 'pending'
    },
    {
      'id': 'a4bf1870-39e2-409b-8180-02629ac86aa5',
      'name': 'Puff Cosgreave',
      'email': 'pcosgreave3@pbs.org',
      'country': 'China',
      'city': 'Liangshui',
      'address': '1st Floor',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_8.jpg',
      'company': 'Trunyx',
      'phoneNumber': '977-619-0375',
      'role': 'Marketing Director',
      'isVerified': true,
      'status': 'active'
    },
    {
      'id': '411ecd06-cc6f-4c36-b511-08645a60f7d6',
      'name': 'Solomon Patinkin',
      'email': 'spatinkin4@ox.ac.uk',
      'country': 'Afghanistan',
      'city': 'Amānzī',
      'address': 'Room 440',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_9.jpg',
      'company': 'Agimba',
      'phoneNumber': '472-375-8644',
      'role': 'Marketing Director',
      'isVerified': false,
      'status': 'active'
    },
    {
      'id': 'c9675a2e-ca6c-4735-8f57-8be5020054c0',
      'name': 'Edy Shirt',
      'email': 'eshirt5@unc.edu',
      'country': 'China',
      'city': 'Zhangtan',
      'address': 'Suite 35',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_10.jpg',
      'company': 'Tazz',
      'phoneNumber': '620-458-1908',
      'role': 'Account Manager',
      'isVerified': true,
      'status': 'active'
    },
    {
      'id': 'c23b7882-175c-4ad1-829d-a5205582673e',
      'name': 'Emanuel Pavolini',
      'email': 'epavolini6@ucoz.com',
      'country': 'France',
      'city': 'Paris 15',
      'address': 'Room 1163',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_11.jpg',
      'company': 'Skaboo',
      'phoneNumber': '229-852-1328',
      'role': 'Data Analyst',
      'isVerified': false,
      'status': 'banned'
    },
    {
      'id': '76bccabf-8244-4525-9ac3-bd89f141c015',
      'name': 'Joly Brace',
      'email': 'jbrace7@joomla.org',
      'country': 'Germany',
      'city': 'Hamburg',
      'address': 'Apt 290',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_12.jpg',
      'company': 'Divanoodle',
      'phoneNumber': '816-113-8007',
      'role': 'Data Analyst',
      'isVerified': true,
      'status': 'active'
    },
    {
      'id': 'fc1f39f5-0043-41cb-b160-b10b24ae9dac',
      'name': 'Wittie Drinkeld',
      'email': 'wdrinkeld8@jimdo.com',
      'country': 'France',
      'city': 'Marseille',
      'address': 'Apt 1625',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_13.jpg',
      'company': 'Meetz',
      'phoneNumber': '660-160-5296',
      'role': 'Customer Service Associate',
      'isVerified': true,
      'status': 'banned'
    },
    {
      'id': '948e04da-3acf-40f0-8bda-356ba0fd2a57',
      'name': 'Carce Beauly',
      'email': 'cbeauly9@oaic.gov.au',
      'country': 'France',
      'city': 'Sélestat',
      'address': 'Room 1688',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_14.jpg',
      'company': 'Zooxo',
      'phoneNumber': '291-770-5856',
      'role': 'Account Manager',
      'isVerified': false,
      'status': 'banned'
    },
    {
      'id': 'ad7283a1-f1a6-4ff9-8555-2b8b66ad9f98',
      'name': 'Clarine Goldstone',
      'email': 'cgoldstonea@amazon.com',
      'country': 'France',
      'city': 'Nancy',
      'address': 'PO Box 99321',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_15.jpg',
      'company': 'Shuffletag',
      'phoneNumber': '878-680-6173',
      'role': 'UX/UI Designer',
      'isVerified': true,
      'status': 'pending'
    },
    {
      'id': '86cc77cf-f7d4-4133-9c93-da6b977ec669',
      'name': 'Graehme Ewers',
      'email': 'gewersb@cocolog-nifty.com',
      'country': 'Ukraine',
      'city': 'Kopayhorod',
      'address': 'PO Box 58480',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_16.jpg',
      'company': 'Voolia',
      'phoneNumber': '548-830-2528',
      'role': 'Developer',
      'isVerified': true,
      'status': 'active'
    },
    {
      'id': 'a85c999b-916b-441d-b239-f7b001445d5b',
      'name': 'Edeline Canepe',
      'email': 'ecanepec@businesswire.com',
      'country': 'Indonesia',
      'city': 'Pasirlimus',
      'address': 'Suite 86',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_17.jpg',
      'company': 'Babbleblab',
      'phoneNumber': '314-895-9590',
      'role': 'Account Manager',
      'isVerified': true,
      'status': 'pending'
    },
    {
      'id': '4a66f2af-e7ec-4813-8db3-f68286ccd216',
      'name': 'Husain Ritmeyer',
      'email': 'hritmeyerd@time.com',
      'country': 'Sweden',
      'city': 'Simrishamn',
      'address': 'PO Box 79454',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_18.jpg',
      'company': 'Realpoint',
      'phoneNumber': '135-931-8704',
      'role': 'Customer Service Associate',
      'isVerified': false,
      'status': 'active'
    },
    {
      'id': 'bdb79cfc-8a95-4696-9385-adc27ab78d03',
      'name': 'Morie Chavez',
      'email': 'mchaveze@hp.com',
      'country': 'Indonesia',
      'city': 'Pendawanbaru',
      'address': 'Suite 38',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_19.jpg',
      'company': 'Kare',
      'phoneNumber': '725-532-2333',
      'role': 'Financial Planner',
      'isVerified': true,
      'status': 'pending'
    },
    {
      'id': '57db53f5-a514-4ab8-8449-fd86d2740246',
      'name': 'Benoite Broadberrie',
      'email': 'bbroadberrief@dion.ne.jp',
      'country': 'Indonesia',
      'city': 'Kema',
      'address': 'Suite 81',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_20.jpg',
      'company': 'Browsetype',
      'phoneNumber': '158-811-9299',
      'role': 'Customer Service Associate',
      'isVerified': true,
      'status': 'pending'
    },
    {
      'id': '73d4a6f7-3e96-43ae-8934-4f9c741c0db9',
      'name': 'Hilde McGarrahan',
      'email': 'hmcgarrahang@clickbank.net',
      'country': 'Angola',
      'city': 'Menongue',
      'address': '8th Floor',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_21.jpg',
      'company': 'InnoZ',
      'phoneNumber': '731-984-5721',
      'role': 'Account Manager',
      'isVerified': true,
      'status': 'banned'
    },
    {
      'id': '9e9d2a99-67cd-4d12-a03e-484d47a3bf28',
      'name': 'Giulia Gosnall',
      'email': 'ggosnallh@flickr.com',
      'country': 'Sweden',
      'city': 'Hägersten',
      'address': '4th Floor',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_22.jpg',
      'company': 'Browsedrive',
      'phoneNumber': '153-335-3521',
      'role': 'Developer',
      'isVerified': true,
      'status': 'pending'
    },
    {
      'id': '4c81f4fa-bfb9-41c1-8d8a-315f30487d5d',
      'name': 'Jude Belverstone',
      'email': 'jbelverstonei@irs.gov',
      'country': 'Yemen',
      'city': 'Sa\'dah',
      'address': 'Room 157',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_23.jpg',
      'company': 'Oyondu',
      'phoneNumber': '751-958-8960',
      'role': 'Account Manager',
      'isVerified': true,
      'status': 'pending'
    },
    {
      'id': '3b5cc71a-a9a8-4b7b-a48d-0a8b69eba8ec',
      'name': 'Sileas Claricoats',
      'email': 'sclaricoatsj@guardian.co.uk',
      'country': 'France',
      'city': 'Nantes',
      'address': 'PO Box 92396',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_24.jpg',
      'company': 'Skinder',
      'phoneNumber': '396-780-7827',
      'role': 'Data Analyst',
      'isVerified': true,
      'status': 'banned'
    },
    {
      'id': 'd46d2af7-03e6-4613-8e2b-d8a73a30cc6e',
      'name': 'Laurette Wildbore',
      'email': 'lwildborek@tripod.com',
      'country': 'Morocco',
      'city': 'Sidi Moussa',
      'address': 'Suite 63',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_25.jpg',
      'company': 'Quinu',
      'phoneNumber': '452-170-5980',
      'role': 'Account Manager',
      'isVerified': true,
      'status': 'pending'
    },
    {
      'id': '9924221e-3cb5-4816-a345-18f5374f5b67',
      'name': 'Virgina Prudence',
      'email': 'vprudencel@yelp.com',
      'country': 'Pakistan',
      'city': 'Kāleke Mandi',
      'address': '18th Floor',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_5.jpg',
      'company': 'Camimbo',
      'phoneNumber': '575-617-2760',
      'role': 'Supply Chain Analyst',
      'isVerified': false,
      'status': 'active'
    },
    {
      'id': '0985160b-9b8a-4bbf-901b-61db4999e845',
      'name': 'Tasia Palmar',
      'email': 'tpalmarm@technorati.com',
      'country': 'Russia',
      'city': 'Sertolovo',
      'address': 'PO Box 20980',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_10.jpg',
      'company': 'Topicblab',
      'phoneNumber': '191-428-5613',
      'role': 'Account Manager',
      'isVerified': false,
      'status': 'pending'
    },
    {
      'id': 'ffdd98b0-fe32-46e6-b39c-ad79662e1901',
      'name': 'Ab de Guerre',
      'email': 'aden@topsy.com',
      'country': 'Indonesia',
      'city': 'Kradinan',
      'address': 'PO Box 40949',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_5.jpg',
      'company': 'Yabox',
      'phoneNumber': '409-956-5854',
      'role': 'Data Analyst',
      'isVerified': false,
      'status': 'active'
    },
    {
      'id': '2dcbdd3c-796a-4afd-9c24-503ed7181898',
      'name': 'Earlie Walsh',
      'email': 'ewalsho@histats.com',
      'country': 'China',
      'city': 'Fenglin',
      'address': 'PO Box 29654',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_6.jpg',
      'company': 'Cogidoo',
      'phoneNumber': '165-620-2695',
      'role': 'Business Analyst',
      'isVerified': true,
      'status': 'banned'
    },
    {
      'id': '1b9b6cb6-9e67-4760-aa1d-f0f4e92f811a',
      'name': 'Ky Kenwyn',
      'email': 'kkenwynp@wordpress.com',
      'country': 'Poland',
      'city': 'Słotowa',
      'address': 'PO Box 80821',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_7.jpg',
      'company': 'Wikibox',
      'phoneNumber': '533-723-3918',
      'role': 'Supply Chain Analyst',
      'isVerified': true,
      'status': 'banned'
    },
    {
      'id': '8e8d01da-53b5-4329-9c0c-2ca23877ca7d',
      'name': 'Anna-maria Bestwick',
      'email': 'abestwickq@fema.gov',
      'country': 'Russia',
      'city': 'Voznesenskaya',
      'address': 'Room 1297',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_8.jpg',
      'company': 'Gabspot',
      'phoneNumber': '168-230-6246',
      'role': 'Marketing Director',
      'isVerified': true,
      'status': 'banned'
    },
    {
      'id': '0fc5121d-993d-4f0a-9917-4b45b4e708e9',
      'name': 'Nedi Goldsby',
      'email': 'ngoldsbyr@theguardian.com',
      'country': 'Indonesia',
      'city': 'Cipari',
      'address': '8th Floor',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_9.jpg',
      'company': 'Teklist',
      'phoneNumber': '613-524-4949',
      'role': 'Marketing Director',
      'isVerified': true,
      'status': 'active'
    },
    {
      'id': '63429290-129d-4b00-ab4b-2d0c5e1c5384',
      'name': 'Bartolomeo Bittlestone',
      'email': 'bbittlestones@howstuffworks.com',
      'country': 'Indonesia',
      'city': 'Kebunan',
      'address': 'Apt 1848',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_10.jpg',
      'company': 'Centidel',
      'phoneNumber': '645-244-0545',
      'role': 'Operations Manager',
      'isVerified': false,
      'status': 'active'
    },
    {
      'id': '6e0c5591-bf40-4ac2-b4fb-b2efde9f760d',
      'name': 'Ysabel Zima',
      'email': 'yzimat@altervista.org',
      'country': 'Indonesia',
      'city': 'Krajan Nglinggis',
      'address': '10th Floor',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_11.jpg',
      'company': 'Dabvine',
      'phoneNumber': '360-124-8142',
      'role': 'Financial Planner',
      'isVerified': false,
      'status': 'active'
    },
    {
      'id': '8e852912-7c93-4007-a2e5-778b0100e624',
      'name': 'Benito Brewers',
      'email': 'bbrewersu@toplist.cz',
      'country': 'Colombia',
      'city': 'Hispania',
      'address': 'PO Box 44397',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_12.jpg',
      'company': 'Skippad',
      'phoneNumber': '970-712-2648',
      'role': 'Financial Planner',
      'isVerified': true,
      'status': 'banned'
    },
    {
      'id': 'e61e9481-b184-4882-9c7e-855346aee705',
      'name': 'Brocky Griffithe',
      'email': 'bgriffithev@zdnet.com',
      'country': 'Mauritius',
      'city': 'Camp Thorel',
      'address': '3rd Floor',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_13.jpg',
      'company': 'Ozu',
      'phoneNumber': '865-508-6579',
      'role': 'Customer Service Associate',
      'isVerified': false,
      'status': 'active'
    },
    {
      'id': 'f1ef62ba-04a2-4687-87b0-425cb5ebeadb',
      'name': 'Alanah Baglow',
      'email': 'abagloww@latimes.com',
      'country': 'Mongolia',
      'city': 'Duut',
      'address': 'Suite 78',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_14.jpg',
      'company': 'Photobug',
      'phoneNumber': '983-777-9408',
      'role': 'Business Analyst',
      'isVerified': true,
      'status': 'pending'
    },
    {
      'id': 'c3e40c44-bf6a-478f-9378-f5af2bf7693c',
      'name': 'Emmery Hackleton',
      'email': 'ehackletonx@example.com',
      'country': 'China',
      'city': 'Sanxianling',
      'address': 'Apt 1436',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_15.jpg',
      'company': 'Devshare',
      'phoneNumber': '905-685-1458',
      'role': 'Financial Planner',
      'isVerified': false,
      'status': 'pending'
    },
    {
      'id': 'c0936df2-f878-423e-8128-e512a62792fc',
      'name': 'Adaline Gibbonson',
      'email': 'agibbonsony@loc.gov',
      'country': 'Kazakhstan',
      'city': 'Arkalyk',
      'address': 'Apt 239',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_16.jpg',
      'company': 'Abata',
      'phoneNumber': '247-941-5106',
      'role': 'Operations Manager',
      'isVerified': false,
      'status': 'pending'
    },
    {
      'id': '9eb3c50c-9981-4453-acf7-668322c8120a',
      'name': 'Ky D\'Alesco',
      'email': 'kdalescoz@va.gov',
      'country': 'China',
      'city': 'Yanweigang',
      'address': 'Apt 632',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_17.jpg',
      'company': 'Skyndu',
      'phoneNumber': '689-499-5112',
      'role': 'Research Scientist',
      'isVerified': false,
      'status': 'pending'
    },
    {
      'id': 'adab2fd8-700c-4c9f-b867-ec54a9b57824',
      'name': 'Allina Grimsell',
      'email': 'agrimsell10@homestead.com',
      'country': 'Russia',
      'city': 'Gramoteino',
      'address': 'Suite 85',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_18.jpg',
      'company': 'Rhycero',
      'phoneNumber': '884-799-1593',
      'role': 'Supply Chain Analyst',
      'isVerified': false,
      'status': 'pending'
    },
    {
      'id': '874e7d86-55e5-4715-89ea-4626583dfc99',
      'name': 'Karita Elcoate',
      'email': 'kelcoate11@scientificamerican.com',
      'country': 'Ukraine',
      'city': 'Vinnytsya',
      'address': 'Suite 53',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_19.jpg',
      'company': 'Wikivu',
      'phoneNumber': '533-672-2886',
      'role': 'Operations Manager',
      'isVerified': false,
      'status': 'pending'
    },
    {
      'id': '5a487e26-2d7f-4b96-82b4-40d27f0fe354',
      'name': 'Steffen Itzchaky',
      'email': 'sitzchaky12@yelp.com',
      'country': 'Russia',
      'city': 'Pestovo',
      'address': 'Apt 1215',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_20.jpg',
      'company': 'Wordify',
      'phoneNumber': '364-343-8744',
      'role': 'Research Scientist',
      'isVerified': false,
      'status': 'banned'
    },
    {
      'id': '08f002e4-d41b-40d9-aaf2-a89f883667f5',
      'name': 'Teodor Chapple',
      'email': 'tchapple13@foxnews.com',
      'country': 'China',
      'city': 'Gouyan',
      'address': 'Apt 1929',
      'avatarUrl': 'https://api-prod-minimal-v510.vercel.app/assets/images/avatar/avatar_21.jpg',
      'company': 'Eayo',
      'phoneNumber': '606-526-7969',
      'role': 'Research Scientist',
      'isVerified': false,
      'status': 'banned'
    } ]
}
